global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'aggregator-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['aggregator-service:8080']
        labels:
          application: 'Aggregator Service Application'

  - job_name: 'collector-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['collector-service:8081']
        labels:
          application: 'Collector Service Application'

  - job_name: 'telegram-bot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['telegram-bot:8083']
        labels:
          application: 'Telegram Bot Application'