spring:
  application:
    name: collector-service

  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus